name: preguntados
description: Taller Semana Lince

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_auth:
  google_sign_in:
  flutter_spinning_wheel:
  giff_dialog:
  get:
  requests:
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gifs/
    - assets/images/categories/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans.ttf